プラグイン名を変更する
agileware-jp/redmine_logs pull request #1
Opened 2018-09-05 09:54 UTC by ryuta-yamauchi

https://insidemine.agileware.jp/issues/12845

2018-09-27 03:55 UTC, zh requested changes
Every Agileware plugin **should depend from ALM** (license management plugin). So in `init.rb`:

~~~ruby
if Redmine::Plugin.installed?(:alm)
  # your plugin code here
  require ....

  Redmine::Plugin.register ...
end
~~~

2018-09-27 03:59 UTC, agilehirakawa commented
@zh このプラグインはLycheeじゃないのでALM無しで動作していいです。

2018-09-27 04:50 UTC, zh approved these changes

2018-09-27 04:53 UTC, zh commented
けどSlackの話で：

> gemだとauthorを複数登録できますけど、Redmine pluginではできないんですよね。
`author 'Originally created by Haruyuki Iida (https://github.com/haru/) / Forked by Agileware Inc. (https://agileware.jp/)'` みたいに併記して、 `author_url` は空にしておくしかない気がします。

2018-09-27 05:07 UTC, urimaro commented
@ryuta-yamauchi 
以下のファイルは修正する必要ありませんか？:thinking:
- app/views/logs/show.html.erb

2018-09-27 10:10 UTC, ryuta-yamauchi commented
> 
> 
> @ryuta-yamauchi
> 以下のファイルは修正する必要ありませんか？🤔
> 
>     * app/views/logs/show.html.erb

念のためこのファイルもredmine_logsからredmine_logs_viewへと変更しました

2018-10-09 10:49 UTC, fkdkent commented
プラグイン名は変更しないことになりました

2018-10-09 10:51 UTC, fkdkent commented
プラグイン名は変更しないことになりましたのでcloseします。

お手数をお掛けして申し訳ありません。ご対応ありがとうございました 🙏

2018-10-09 10:51 UTC, closed without merging