Update init.rb
agileware-jp/redmine_logs pull request #4
Opened 2018-10-09 09:58 UTC by fkdkent

2018-10-09 13:08 UTC, urimaro requested changes

2018-10-09 13:08 UTC, urimaro commented on init.rb
>    requires_redmine :version_or_higher => '3.0.0'
Lychee Redmineのサポート対象が `>= 3.2.0, < 4.0.0` なので、`3.2.0` にした方が良さそう。
Redmine 3.0系、3.1系のテストしないですよね…
また、Rubyのバージョンとか指定できるんでしょうか？:thinking:

2018-10-09 13:31 UTC, fkdkent commented on init.rb
>    requires_redmine :version_or_higher => '3.0.0'
`requires_redmine`を設定すると、対象外のバージョンではプラグインを読み込んだ時点で例外が送出されます。`3.2.0`未満をサポートすることはないはずですが、サポート外のバージョンであえて起動不能にする必要もないかと思いました。

init.rbではRubyのバージョン指定はできません。

2018-10-10 01:36 UTC, urimaro commented on init.rb
>    requires_redmine :version_or_higher => '3.0.0'
了解です。
改修内容を考えると、3.0、3.1でも動作すると思いますし、Agileware謹製ではないので、そのままでも良いかもしれませんね。

2018-10-10 01:37 UTC, urimaro approved these changes

2018-10-16 08:53 UTC, merged