Update readme
agileware-jp/redmine_logs pull request #5
Opened 2018-10-09 10:14 UTC by fkdkent

2018-10-09 12:48 UTC, urimaro requested changes

2018-10-09 12:48 UTC, urimaro commented on README.md
> +cd <Redmine Home>
`Redmine Install Dir` と `Redmine Home` は同じディレクトリですよね？
同じディレクトリならば、同じ言葉( `path_to_redmine` など)を使った方が良いと思います。
一連のコマンドなのであれば `cd ..` で良いと思います。

2018-10-09 12:48 UTC, urimaro commented on README.md
> +bundle exec rake redmine:plugins:assets RAILS_ENV=production
上記2コマンドは `bundle exec rake redmine:plugins` にまとめられると思います。

2018-10-09 12:48 UTC, urimaro commented on README.md
> +and restart Redmine.
空行を入れたほうが良さそう。

2018-10-09 12:48 UTC, urimaro commented on README_zh.md
> +bundle exec rake redmine:plugins:assets RAILS_ENV=production
コマンドについては、英語版同様です。

2018-10-09 12:48 UTC, urimaro commented
日本語版のREADMEは作らないんでしょうか？:thinking:

2018-10-09 13:46 UTC, fkdkent commented on README.md
> +cd <Redmine Home>
dab1f2ce8b4da0bc2a04804805c98f0bd9b31fe1 で修正しました。

2018-10-09 13:47 UTC, fkdkent commented on README.md
> +bundle exec rake redmine:plugins:assets RAILS_ENV=production
e6d8bcc で修正しました。

2018-10-09 13:47 UTC, fkdkent commented on README.md
> +and restart Redmine.
4420d7d で修正しました。

2018-10-09 13:47 UTC, fkdkent commented on README_zh.md
> +bundle exec rake redmine:plugins:assets RAILS_ENV=production
e6d8bcc で修正しました。

2018-10-09 13:55 UTC, fkdkent commented
コメントありがとうございます。修正しました。

日本語版については特に必要ないかと思っています。英語版の文章は拙いですが、何を書いているのか理解できないということはないと思います。

中国語版は @maro-kt さんが追加されていたのでそのまま引き継いでいますが、他の人には変更が難しいので、maro-ktさんに継続してメンテナンスする余力がなさそうなら追加を見送った方がいいかもしれないですね。

2018-10-10 01:44 UTC, urimaro commented
日本語版について、了解です。
中国語版についてですが、そのままで良いと思います。
OSSなので、メンテし続け「なければならない」ということはないですし、「適切でなければPRが来る」ことを期待しても良さそうに思います。

2018-10-10 04:22 UTC, urimaro approved these changes

2018-10-16 08:53 UTC, merged